=== jantic/Intelligent-Media-Player/IntelligentMediaPlayer/PlaylistManagement/PlaylistModifier.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="PlaylistModifier">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="Type">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="WMPAttribute"/>
              <xs:enumeration value="LastFM"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="UI">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DisplayName" type="xs:string"/>

              <xs:element name="Inputs">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="Input" minOccurs="1" maxOccurs="5">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ID">
                            <xs:simpleType>
                              <xs:restriction base="xs:unsignedInt">
                                <xs:minInclusive value="1"/>
                                <xs:maxInclusive value="5"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="UILabel" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Action">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Add"/>
              <xs:enumeration value="Subtract"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        

        <xs:element name="Method">
          <xs:complexType>
            <xs:choice>

              <xs:element name="MediaAttributeMatch">
                <xs:complexType>
                  <xs:sequence>
                    
                    <xs:element name="AttributeMappings">
                      <xs:complexType>
                        <xs:sequence>

                          <xs:element name="Mapping" minOccurs="1" maxOccurs="5">
                            <xs:complexType>
                              <xs:sequence>

                                <xs:element name="ID" type="xs:unsignedInt"/>
                                <xs:element name="WMP_Attribute" type="xs:string"/>
                                <xs:element name="InputID" type="xs:unsignedInt"/>
                                
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>

                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              


              <xs:element name="LastFMrequest">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="RequestURL">
                      <xs:complexType>
                        <xs:sequence>
                          
                          <xs:element name="TemplateURL" type="xs:string"/>
                          
                          <xs:element name="TemplateMappings">
                            <xs:complexType>
                              <xs:sequence>

                                <xs:element name="Mapping" minOccurs="1" maxOccurs="5">
                                  <xs:complexType>
                                    <xs:sequence>
                                      
                                      <xs:element name="ID" type="xs:unsignedInt"/>
                                      <xs:element name="ToReplace" type="xs:string"/>
                                      <xs:element name="InputID" type="xs:unsignedInt"/>
                                      
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    
                    
                    

                    <xs:element name="Response">
                        <xs:complexType>
                          <xs:sequence>
                            
                            <xs:element name="Outputs">
                              <xs:complexType>
                                <xs:sequence>

                                  <xs:element name="Output" minOccurs="1" maxOccurs="5">
                                    <xs:complexType>
                                      <xs:sequence>
                                        
                                        <xs:element name="ID" type="xs:unsignedInt"/>
                                        <xs:element name="WMP_Attribute" type="xs:string"/>
                                        <xs:element name="xPath" type="xs:string"/>
                                        
                                      </xs:sequence>
                                    </xs:complexType>
                                  </xs:element>
                                  
                                </xs:sequence>
                              </xs:complexType>
                            </xs:element>
                            
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>

                    
                    
                    
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              </xs:choice>
          </xs:complexType>
         </xs:element>
  
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== jantic/Intelligent-Media-Player/IntelligentMediaPlayer/PlaylistModifierPlugins/LastFM_ArtistTopTracks.xml
<?xml version="1.0" encoding="utf-8" ?>

<PlaylistModifier
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="..\PlaylistManagement\PlaylistModifiers\PlaylistModifier.xsd">

  <Type>LastFM</Type>
  
  <UI>
    <DisplayName>Last.FM Artist Top Tracks</DisplayName>

    <Inputs>
      <Input>
        <ID>1</ID>
        <UILabel>Artist</UILabel>
      </Input>
    </Inputs>
  </UI>

  <Action>Add</Action>

  <Method>
    <LastFMrequest>
      <RequestURL>
        <TemplateURL>http://ws.audioscrobbler.com/2.0/artist/[Artist]/toptracks.xml </TemplateURL>
        <TemplateMappings>
          <Mapping>
            <ID>1</ID>
            <ToReplace>[Artist]</ToReplace>
            <InputID>1</InputID>
          </Mapping>
        </TemplateMappings>
      </RequestURL>

      <Response>
        <Outputs>
          <Output>
            <ID>1</ID>
            <WMP_Attribute>Artist</WMP_Attribute>
            <xPath>//toptracks/track/artist/name</xPath>
          </Output>
          <Output>
            <ID>2</ID>
            <WMP_Attribute>Title</WMP_Attribute>
            <xPath>//toptracks/track/name</xPath>
          </Output>
        </Outputs>
      </Response>
    </LastFMrequest>
  </Method>
  
  
</PlaylistModifier>

=== jantic/Intelligent-Media-Player/IntelligentMediaPlayer/PlaylistModifiers/LastFM_UserTopAlbums.xml
<?xml version="1.0" encoding="utf-8" ?>

<PlaylistModifier
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="..\PlaylistManagement\PlaylistModifier.xsd">

  <Type>LastFM</Type>

  <UI>
    <DisplayName>Last.FM User Top Albums</DisplayName>

    <Inputs>
      <Input>
        <ID>1</ID>
        <UILabel>Last.FM User</UILabel>
      </Input>
    </Inputs>
  </UI>

  <Action>Add</Action>

  <Method>
    <LastFMrequest>
      <RequestURL>
        <TemplateURL>http://ws.audioscrobbler.com/2.0/?method=user.gettopalbums&amp;user=[user]&amp;api_key=e295ea662af320c44101419cb30cfffe</TemplateURL>
        <TemplateMappings>
          <Mapping>
            <ID>1</ID>
            <ToReplace>[user]</ToReplace>
            <InputID>1</InputID>
          </Mapping>
        </TemplateMappings>
      </RequestURL>

      <Response>
        <Outputs>
          <Output>
            <ID>1</ID>
            <WMP_Attribute>Album</WMP_Attribute>
            <xPath>//topalbums/album/name</xPath>
          </Output>
          <Output>
            <ID>2</ID>
            <WMP_Attribute>Artist</WMP_Attribute>
            <xPath>//topalbums/album/artist/name</xPath>
          </Output>
        </Outputs>
      </Response>
    </LastFMrequest>
  </Method>
</PlaylistModifier>

=== jantic/Intelligent-Media-Player/IntelligentMediaPlayer/Playlist Modifier Plugins/WMP/WMP_ArtistName.xml
<?xml version="1.0" encoding="utf-8" ?>

<PlaylistModifier 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="..\..\Playlist Management\PlaylistModifiers\PlaylistModifier.xsd">

  <Type>WMPAttribute</Type>
  
  <UI>
    <DisplayName>Artist Name</DisplayName>

    <Inputs>
      <Input>
        <ID>1</ID>
        <UILabel>Artist</UILabel>
      </Input>
    </Inputs>
  </UI>

  <Action>Add</Action>

  <ModifierKey>WMP_ArtistName</ModifierKey>

  <Method>
    <MediaAttributeMatch>
      <AttributeMappings>
        <Mapping>
          <ID>1</ID>
          <WMP_Attribute>Author</WMP_Attribute>
          <InputID>1</InputID>
        </Mapping>
      </AttributeMappings>
    </MediaAttributeMatch>
  </Method> 
  
</PlaylistModifier>

=== jantic/Intelligent-Media-Player/IntelligentMediaPlayer/Playlist Modifier Plugins/LastFM/LastFM_SimilarTracks.xml
<?xml version="1.0" encoding="utf-8" ?>

<PlaylistModifier
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="..\..\Playlist Management\PlaylistModifiers\PlaylistModifier.xsd">

  <Type>LastFM</Type>
  
  <UI>
    <DisplayName>Last.FM Artists by Tag</DisplayName>

    <Inputs>
      <Input>
        <ID>1</ID>
        <UILabel>Tag</UILabel>
      </Input>
    </Inputs>
  </UI>

  <Action>Add</Action>

  <ModifierKey>LastFM_SimilarTracks</ModifierKey>

  <Method>
    <LastFMrequest>
      <RequestURL>
        <TemplateURL>http://ws.audioscrobbler.com/2.0/?method=tag.gettopartists&amp;tag=[Tag]&amp;api_key=e295ea662af320c44101419cb30cfffe </TemplateURL>
        <TemplateMappings>
          <Mapping>
            <ID>1</ID>
            <ToReplace>[Tag]</ToReplace>
            <InputID>1</InputID>
          </Mapping>
        </TemplateMappings>
      </RequestURL>

      <Response>
        <Outputs>
          <Output>
            <ID>1</ID>
            <WMP_Attribute>Artist</WMP_Attribute>
            <xPath>//topartists/artist/name</xPath>
          </Output>
        </Outputs>
      </Response>
    </LastFMrequest>
  </Method>
</PlaylistModifier>

=== jantic/Intelligent-Media-Player/IntelligentMediaPlayer/PlaylistModifiers/LastFM_AlbumsByTag.xml
<?xml version="1.0" encoding="utf-8" ?>

<PlaylistModifier
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="..\PlaylistManagement\PlaylistModifier.xsd">

  <Type>LastFM</Type>

  <UI>
    <DisplayName>Last.FM Albums by Tag</DisplayName>

    <Inputs>
      <Input>
        <ID>1</ID>
        <UILabel>Tag</UILabel>
      </Input>
    </Inputs>
  </UI>

  <Action>Add</Action>

  <Method>
    <LastFMrequest>
      <RequestURL>
        <TemplateURL>http://ws.audioscrobbler.com/2.0/?method=tag.gettopalbums&amp;tag=[Tag]&amp;api_key=e295ea662af320c44101419cb30cfffe </TemplateURL>
        <TemplateMappings>
          <Mapping>
            <ID>1</ID>
            <ToReplace>[Tag]</ToReplace>
            <InputID>1</InputID>
          </Mapping>
        </TemplateMappings>
      </RequestURL>

      <Response>
        <Outputs>
          <Output>
            <ID>1</ID>
            <WMP_Attribute>Album</WMP_Attribute>
            <xPath>//topalbums/album/name</xPath>
          </Output>
          <Output>
            <ID>2</ID>
            <WMP_Attribute>Artist</WMP_Attribute>
            <xPath>//topalbums/album/artist/name</xPath>
          </Output>
        </Outputs>
      </Response>
    </LastFMrequest>
  </Method>
</PlaylistModifier>

=== jantic/Intelligent-Media-Player/IntelligentMediaPlayer/PlaylistModifierPlugins/WMP_Year.xml
<?xml version="1.0" encoding="utf-8" ?>

<PlaylistModifier 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="..\PlaylistManagement\PlaylistModifiers\PlaylistModifier.xsd">

  <Type>WMPAttribute</Type>
  
  <UI>
    <DisplayName>Year</DisplayName>

    <Inputs>
      <Input>
        <ID>1</ID>
        <UILabel>Year</UILabel>
      </Input>
    </Inputs>
  </UI>

  <Action>Add</Action>

  <Method>
    <MediaAttributeMatch>
      <AttributeMappings>
        <Mapping>
          <ID>1</ID>
          <WMP_Attribute>ReleaseDateYear</WMP_Attribute>
          <InputID>1</InputID>
        </Mapping>
      </AttributeMappings>
    </MediaAttributeMatch>
  </Method> 
  
</PlaylistModifier>

=== jantic/Intelligent-Media-Player/IntelligentMediaPlayer/Playlist Modifier Plugins/LastFM/LastFM_SimilarArtists.xml
<?xml version="1.0" encoding="utf-8" ?>

<PlaylistModifier
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="..\..\Playlist Management\PlaylistModifiers\PlaylistModifier.xsd">

  <Type>LastFM</Type>
  
  <UI>
    <DisplayName>Last.FM Similar Artists</DisplayName>

    <Inputs>
      <Input>
        <ID>1</ID>
        <UILabel>Artist</UILabel>
      </Input>
    </Inputs>
  </UI>

  <Action>Add</Action>

  <ModifierKey>LastFM_SimilarArtists</ModifierKey>

  <Method>
    <LastFMrequest>
      <RequestURL>
        <TemplateURL>http://ws.audioscrobbler.com/2.0/?method=artist.getsimilar&amp;artist=[Artist]&amp;api_key=e295ea662af320c44101419cb30cfffe </TemplateURL>
        <TemplateMappings>
          <Mapping>
            <ID>1</ID>
            <ToReplace>[Artist]</ToReplace>
            <InputID>1</InputID>
          </Mapping>       
        </TemplateMappings>
      </RequestURL>

      <Response>
        <Outputs>
          <Output>
            <ID>1</ID>
            <WMP_Attribute>Artist</WMP_Attribute>
            <xPath>//similarartists/artist/name</xPath>
          </Output>
        </Outputs>
      </Response>
    </LastFMrequest>
  </Method>
</PlaylistModifier>
